# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robin Onsay
email: onsayrobin@gmail.com
description: "Driven by a lifelong fascination with human exploration beyond Earth, Robin graduated from Michigan State University with a Bachelor’s in Computer Engineering. She excels at bridging software and hardware within real‑time embedded systems for spacecrafts, where reliability and precision are paramount."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robinonsay.me" # the base hostname & protocol for your site
twitter_username: robinonsay
github_username:  robinonsay
linkedin_username: robinonsay

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
